django_survey/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('surveys/', include('surveys.urls')),
    path('admin/', admin.site.urls),
]

surveys/urls.py
from django.urls import path
from . import views

app_name = 'surveys'
urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('<int:survey_id>/', views.detail, name='detail')
]

surveys/models.py
from django.db import models



class Survey(models.Model):
    survey_title = models.CharField(max_length=200)
    published= models.DateTimeField(default=None)
    def __str__(self):
        return self.survey_title

class Question(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    question_title = models.CharField(max_length=200)
    published = models.DateTimeField('date published')

surveys/views.py
from django.http.response import Http404
from django.shortcuts import render
from django.http import HttpResponse
from .models import Survey
from django.shortcuts import render 


def index(request):
    survey_list = Survey.objects.order_by('-published')[:5]
    context = {'survey_list': survey_list}
    return render(request, 'surveys/index.html', context)

def detail(request, survey_id):
    try:
        survey = Survey.objects.get(pk=survey_id)
    except Survey.DoesNotExist:
        raise Http404('Survey does not exist')
    return render(request, 'surveys/detail.html', {'survey': survey})

def create(request):
    return HttpResponse(f'You have arrived at the create page')

surveys/templates/surveys/detail.html
<h1>
    Survey Detail Page
</h1>

{% if survey %}
    <div>
        {{survey.survey_title}}
    </div>
{% endif %}

surveys/templates/surveys/index.html
<div>
 Create a new survey

 <div>
  <form action="{% url 'surveys:create' %}" method="post">
  {% csrf_token %}

    <label for="survey_title">Enter title of survey</label>
    <input type="text" id="survey_title" required>
    <input type="submit">
  </form>
 </div>

</div>

<div>
 {% if survey_list %}
    <ul>
      {% for survey in survey_list %}
        <li>
           Title:
            <a href="{% url 'surveys:detail' survey.id %}">
             {{survey.survey_title}} 
            </a>
            Published: {{survey.published}}
        </li>
      {% endfor %}
    </ul>
 {% endif %}
</div>